:linkcss:
:stylesdir: css/
:stylesheet: styles.css

:toc:
:toclevels: 4
:toc-title: Содержание

==  Система торговли Березка

Версия для Индивидуального Чемпионата Gambler.

=== Основные открытия
1C +
   а) 12-14 NT - (слабый вариант) +
   б) 12-16 3-цвет без !d - (слабый вариант) +
   в) 17+ неравномерный (в том числе форсинг до гейма) (сильный вариант) +
   г) 18+ любой (в том числе форсинг до гейма) (сильный вариант). +

1D  12-16 4+!d, расклад неравномерный (в том числе и при 4ке!d и 5+!c), либо 5+!d в любом раскладе

1HS  11-16 5+ натурально (после паса партнера допускается существенно ослабленное открытие)

1N  15-17, исключает мажорные пятерки, расклад 5-4 по минорам и минорную 6ку.

2C       12-16, 6+!c или 5+!c =4!h/!s, исключает 4!d

2D     6-10, 6+ в неизвестном мажоре. Отрицает ренонсы, 4ку в другом мажоре

2HS    5+5+ !h!s с минором, сила 6-10

2N      5+-5+ в минорах, сила 6-10

3N      Gambling с ТКДхххх в миноре и с 1 боковым контролем

=== Открытие 1C

    а) 12-14 NT
    б) 12-16 3-цвет без !d
    в) 17+ неравномерный (в том числе форсинг до гейма)
    г) 18+ любой (в том числе форсинг до гейма).

1C-1D +
а) негатив (0-7) +
б) 7-9 без 4-к в мажоре, обычно минорная рука, не подходящая для ответа 1N или 2CD +
в) 16+ PC без 4-к в мажоре, 5-к в миноре (фальшнегатив) +

1C-1D- ? +
1HS - лучший мажор (от 3-ки), может быть минимум сильного варианта, не форсирует; +
1N - 18-21 NT (на что есть стейман 2!c и трансферы с обычными ответами); +
2C - FG, на что 2D - минимум негатива, остальное натурально; +
2DHS,3C - натурально, сильный вариант, не форсирует, но сильно инвитирует; +
2N - 22-24 NT (на что есть стейман 3C и трансферы 3DH) +
3N - контракт, просьба пасовать, если не фальшнегатив. +

1C-1HS (от 4ки, 8+)- ? +
1C-1HS-1N - слабый вариант, после этого есть check-back 2C: +

1C-1HS-1N-2C- ?
2D/2N - min/max с дублетом в масти партнера, +
`2 в мажор партнера` - min с 3-картным фитом, +
`2 в другой мажор` - max с 3-картным фитом; +

  Check-back задается с силой от инвита и, как минимум, с пятеркой в мажоре. Любой максимальный ответ открывающего на check-back форсирует гейм (инвит принят).
	Также, перескакивание отвечающим своего мажора форсирует гейм (двух инвитов не бывает).

Например: +
1C-1H-1N-2C!-2D!-2N ФГ +
*Исключение* после Check-back от отвечающего не форсирует 3C,
показывает 8-10 очков от 6 треф, т.е. +
1C-1H-1N-2C!-2D!-3C - не форсирует, показывает =4 черв, 6+ треф.

1C-1HS-1N-2D - не форсирует

1C-1HS-2C - одвротка, вопрос о качестве мажора и силе, ФГ. Обещает не менее триплета в мажоре партнера:

1C-1HS-2C!- ? +
2D - 4ка, минимум (8-10) +
2H - 4ка, максимум (11+) +
2S - 5ка, минимум +
2N 5ка, максимум +
3CD - максимум, =4ка в мажоре, 5+!c!d

Изменения при интервенции: +
Если вмешался левый оппонент открывающего, одвротка сохраняется: 1C-(1H)-1S-(P)-2C! одвр. +
Если вмешался правый опп открывающего, одвротки нет: 1C-(P)-1H-(1S)-2C - нат.

Если входят на одвротку, *все ответы становятся натуральными , включая контру и реконтру*.

1C-1HS-2D, 1C-1S-2H - натурально, сильный вариант, ФГ. На что повторение отвечающим своего мажора обещает 6-ку (!) +
1C-1H-2H, 1C-1S-2S - =4ка в мажоре, слабый вариант, нефорс. На что 2N, `3 в мажор` от отвечающего инвит, остальные заявки ФГ. +
1C-1H-1S - не исключает сильного варианта, сохраняется чек-бэк 2C. +
1C-1HS-2N - нат, 18+ (в секвенции 1C-1H ребид 2N не отрицает 4-ки !s); +

`3 в мажор партнера` - 14-16, расклад 4-4-1-4;

Двойной прыжок - сплинтер.

1C-1N (7-10)- ? +
2CDHS - натурально от 5ки, 17+, форсирует; +
2N - 15-16, расклад 4-4-1-4; +
`3 в масть` - устанавливает козырную масть, шлемовая торговля.

1C-2CD (10+, исключает мажорные 4-ки) - ? +
2DHS - натурально, форсгейм +
2N, `3 в минор партнера` - не форсирует, минимум. На что любая заявка отвечающего кроме 3N ФГ. +
`3 в новую масть со скачком` - устанавливает согласованную масть, шлемовая торговля. +
`Фит на уровне 4` - форсирует, шлемовая торговля; +

1C-2HS - FG от хорошей 6-ки, фит дается от второй фигуры, остальное натурально. После повторения отвечающим мажора на 3-м уровне, масть становится согласованной, 4N блэквуд на ней. +
1C-3CD - натурально, инвит с хорошей мастью ( в т.ч. и после интервенции ЛО открывающего контрой или 1 в масть); +
1C-3HS - инвит в 4!h/!s с длинной мастью; +
1C-3N - натурально.

==== Изменения при интервенции на 1C
1C-(DBL)- ?? +
P/1D - негатив с 4!c/без 4!c; +
1H/1S от 4-ки, может быть и сильная рука (check-back сохраняется) +
RDBL - 10+, NT, устанавливает ситуацию форсирующего паса +
_(в ситуации форсирующего паса все контры становятся наказательными)_ +
1N,2N,3N натурально
2CD 7-11 от 5-ки +
2HS 4-7 от 5-ки +
`заявки на уровне 3` сохраняют значения

1C-(1D)- ?? +
DBL без мажоров, 8+ HCP +
1HS - от 4-ки, форсирует на круг, может быть и сильная рука (check-back сохраняется) +
2D - двухмастка с пикой (пика-черва или пика-трефа) +
2CHS - не форсирует +
2N двухмастка с младшими мастями (черва и трефа) +
`заявки на уровне 3 (кроме 3!d)` - как без интервенции

1C-(1HS)- ?? +
1S после 1C-(1H) от 5ки пик, форсирует на круг +
`контра спутник`, в слабом варианте обещает 4 в другом мажоре либо ФГ в любом раскладе (показывается дальнейшим ребидом отвечающего в другую масть) +
`кюбид` на 2ом уровне краткость, от 55 в другом мажоре и любом миноре +
`другая масть на 2 уровне` нат, не форсирует +
2N 11-12 без 4ки в др мажоре, с держкой +
`заявки на уровне 3 (кроме кюбида)`- как без интервенции +

Если оппонент входит после секвенции 1C-(P)-1HS, то играется контра-трешка до уровня 2 в нашем мажоре

1C-(2D-Multi)-DBL-(2HS)- ?? +
DBL - натуральная (4-ка в заявленной оппонентом масти).

=== Открытие 1D - 12-16, 4+!d, расклад неравномерный, либо 5+ в любом раскладе

1D-1HS (6+PC от 4ки)- ?

В секвенциях 1D-1H-1N, 1D-1S-1N, 1D-1H-1S есть чек-бэк 2C, ответы стандартные

1D-1S-2D-2H - полунат, форс на круг +
1D-1HS-2N max, 6!d, нет 3ки в мажоре партнера +
1D-1HS-3D max, 6!d, 3ка в мажоре партнера

1D-2CD 10+PC, 4+!c!d, форс на круг, исключает мажорные 4, после чего показываем держки натурально. +
В секвенции 1D-2D назначение отвечающим 2N форсирует, 3D не форсирует +
После 1D-2C единственная минимальная заявка открывшего - 2D (не удлиняет бубну), остальные ответы открывшего форсируют гейм. +
1D-2C-2D-2N,3C FG +

1D-2N,3C инвит +
1D-2HS ФГ от хорошей 6 +
1D-3D - блок 0-9 +
1D-3HS сплинтер на бубне

==== Изменения при интервенции на 1D
1D-(DBL)-2D - не форс, но сильнее, чем 3D +
1D-(DBL)-2HS блок +
1D-(DBL)-2C - NF +
1D-(1H)-2S - блок +
1D-(DBL)-RDBL 10+, устанавливает ситуацию форсирующего паса. +
1D-(1HS)-3C инвит +
1D-(1HS)-3D - блок

=== Открытие 1H/1S - 11-16, 5+ (после паса партнера допускается существенно ослабленное открытие)
1H-1S - 6+ от 4ки +
В секвенции 1H-1S-1N имеется check-back +
1H-1S-2N max, 6!h без трешки !s +
1H-1S-3H max, 6!h с трешкой !s

1HS-1N 6-9 без фита

1H-2S - ФГ от хорошей 6ки

1HS-2CD, 1S-2H - 10+, от 4ки, форсирует на круг

_После этого у открывающего не форсируют только заявки не выше уровня его мажора на 2ом уровне. Все остальные заявки показывают надвышки и форсируют гейм. +
От отвечающего ребид 2N *ВСЕГДА* форсирует гейм, инвиты через 3ий уровень, например:_

1S-2D-2N,3CD - нат, форсгейм +
1S-2H-2S-2N форсгейм, в том числе м.б. с фитом, просьба доописаться +
1H-2C-2H-3C- инвит в 3NT +
1H-2C-2H-3H- инвит в 4!h и т.п.

1HS-2N - инвит с 4-картным фитом. +
1HS-3CD - масть+фит, сила от инвита. +
1S-3H - инвит с хорошей 6-кой, это же значение сохраняется после контры ЛО открывающего. +
1H-3S,4CD - сплинтер на черве +
1HS-3N - контракт +
1S-4H - сплинтер

==== Измения в интервенции

После входа врага мастью сплинтер сохраняется только в масти врага; масть с прыжком показывает масть+фит. После вызывной контры от ЛО открывшего заявка, которая без контры была бы сплинтером, теперь также показывает масть+фит.

===== Друри - 2C
Друри 2C (вопрос о силе и раскладе) используется после открытия партнера 1M на 3ей руке или его интервенции на 1C или ненатуральную 1D. Если партнер вошел на натуральное открытие 1DH, то Друри - это 2DH, а 2C - натурально.
Эта конвенция используется только если ЛО открывшего (вошедшего) спасовал.
Друри задается с силой от инвита и не обещает (но и не исключает) фит.

Ответы на Друри 2C: +
2D - ослабленное открытие (8-10); +
`2 в мажор открытия` (или 2H после открытия 1S) 11-13, усилений не обещает; +
`Заявка выше` - максимум открытия (14-16);

После открытия 1M на 3й руке +
1M-2N инвит с как минимум 4картным фитом.

=== Открытие 1N (15-17). Невозможны мажорные 5ки, расклад 5-4 по минорам и минорная 6
2C - Стейман, на который у открывшего имеется 3 ответа - 2D, 2H, 2S

1N-2C-2D-2H - =5ка ч,=4ка п, не форсирует +
1N-2C-2D-2S - =5ка п,=4ка ч, не форсирует +
1N-2C-2D-2N - инвит

2D/2H - Трансфер в !h/!s со стандартными ответами +
Новая масть после трансфера - ФГ

2S - Инвит к 3NT или трансфер в !c (на что 2N - min, 3C - max); +
1N-2S-2N/3C-3HS - 5+!c, =4ка в мажоре, шлемовая торговля.

2N - Трансфер в !d (на что 3D - min, 3C - max);

3CDHS - 5+ со шлемовыми намерениями, на что: +
3N нет фита, `подъем масти` минимум, `другая масть` кюбид и максимум с фитом. +
Далее 4N от отвечающего блэквуд на его масти.

3N,4HS - контракт;

4N инвит в 6NT

==== Изменения, если партнер пасовал
P-1N-3CDHS - инвит к 3NT, масть типа ТДxxxx или КДxxxxx, просит дополнения в виде второй фигуры или длины.

==== Изменения при интервенции
Если оппоненты вмешались контрой на 1N, то: +
P для игры (открывающий может сам убежать в 5, или дать реконтру без пятерок) +
RDBL 8+, устанавливает ситуацию форсирующего паса +
`2 масть` натурально, побег +
`3 масть` - блок +
2N двумастная, обычно минорная рука

Если оппоненты вмешались мастью на 2 уровне, то: +
DBL призывная, может содержать ФГ +
`2 масть` не форсирует +
`3 масть` инвит

Если оппоненты вмешались мастью на 3 уровне, то DBL ненаказательная, но может быть отпасована, при соответствующей руке.

После оппоненты контрят наш Стейман (показывая трефу): +
показ мажорных четверок является приоритетным +
P - приличная трефа (4-ка с двумя онерами) +
RDBL - 5-ка !c.

=== Открытие 2C (12-16), Precision, 6+!c или 5+!c,=4!h/!s
2C-2D вопрос, сила от инвита.

2C-2D-2HS - натурально 4-ка, на это: +
`3 в мажор партнера` инвит с фитом +
2N инвит без фита +
3C - нат, инвит +
`Новая масть` - ФГ

2C-2D-2N - одноцвет, max (количество задержек несущественно), на это: +
3C - форсирует; +
3DHS - 5+ натурально, форсгейм

2C-2D-3C - одноцвет, min, на это: +
3DHS - 5+ натурально, форсинг до гейма;

2C-2D-3D - трефа типа ТКДхххх и нет контролей сбоку. На это: +
4C, 3N сайн-оф. +
3HS - натурально, форсинг до гейма +
`остальное` кюбиды на трефе

2C-2D-3HS - максимум, 6-4, концентрация в длинных мастях.

Другие ответы на открытие 2C: +
2C-2HS - 5+ натурально, не форсирует (но приглашает торговать); +
2C-2N - натурально, инвит; +
2C-3C - 6-10, фит; +
2C-3DHS - натурально от 6ки, хорошая масть, инвит в 3NT; +
2C-4C - блок. +
2C-4HS - контракт

==== После вызывной контры врага на 2C
RDBL - от 10 НСР; +
P, затем `вызывная контра` - 6-9; +
2D - слабость с бубновой мастью.

=== Открытие 2D (Малти), 6-10, 6ка в неизвестном мажоре. Отрицает ренонсы, 4ку в другом мажоре
2D-2HS, 3HS, 4H - до длины партнера

2D-4S - контракт

2D-2N - вопрос от инвита с ответами, на что: +
3C/3D - !h/!s, максимум, создает ситуацию ФГ; +
3H/3S - натурально, минимум, +
3N - масть вида ТКДххх

2D-3CD - натурально, форсирует (практически не используется);

==== После интервенции
2D-(DBL)-? +
P - своя бубна +
RDBL назови мажор +
2HS натурально, нефорс +
Остальные заявки сохраняют значение.

2D-(2HS)-? +
DBL до длины

=== Открытие 2H/2S Двуцвет (5+-5+) !h/!s с минором при силе до открытия (6-10)
В благоприятной зональности или с третьей руки возможна 4 в миноре.

2H-2S - нат, не форсирует

2HS-3C - слабый поиск минора,

2H-3H - блок +
2HS-2N сильный вопрос, от инвита, с ответами: +
3C - минимум с !c +
3D - минимум с !d +
3H - максимум с !c +
3S - максимум с !d +
После ответов 3HS мы в ФГ.

2H-2N-3C-3H - инвит

==== После интервенции на 2HS
DBL на 2-м уровне - до минора, на 3-м - наказательная.

=== Открытие 2N. 5+-5+ в минорах при силе до открытия (~7-11)
2N-3C - до минора +
2N-3HS - натурально, форсирует +
2N-4CD - инвит

=== Блоки
В выгодной зональности кроме второй руки - random. +
В равной зональности классические и random с третьей руки. +
В невыгодной зональности ТКВхххх либо ТКДхххх +
После блока новая масть форсирует. Во всех сомнительных ситуациях согласованной считается масть блока.

=== Открытие 3N
Gambling с ТКДхххх в миноре и с 1 боковым контролем. +
4C - слабость, нежелание играть 3NT; +
4D - вопрос о краткости, с ответами:

* 4H,4S - в черве, пике
* 4N без краткости
* 5C - краткость бубен
* 5D - краткость треф


=== Общие принципы борьбы с интервенцией оппонентов

*Во всех сомнительных ситуациях контра, которая может быть негативной, считается негативной.*

*Новая масть 2-м уровне не форсирует даже со скачком (3-9 PC)..*

*Заявки на 1-ом и 3-ем уровне сохраняют значение, как и без интервенции. Масть врага на 2ом уровне краткость, на 3-м уровне - вопрос о задержке.*

==== После вызывной контры на открытие 1 в масть
RDBL 10+, прежде всего имеет целью наказать врага на низком уровне (в случае мисфита и/или неблагоприятной для оппонентов зональности). Создает ситуацию форсирующего паса (оппоненты уже не могут разыгрывать контракт без контры).

==== После входа мастью на открытие
DBL негативная, обещает 4ку в другом мажоре или ФГ в любом раскладе.

==== Контра-фит
После ответа на 1-м уровне используется контра-фит до уровня 2 в нашем мажоре, например: +
1D-(P)-1H-(2C)-DBL - 3 карты в черве. +
Также используется реконтра-фит, например: +
1CDH-(P)-1S-(DBL)-RDBL - 3 карты в пике.

==== Наказательные контры
после установления ситуации ФГ или нашего ответа 1N, после силовой реконтры.

==== После натурального входа 1N на наше открытие на 1ом
1CD-(1N) как на открытие 1N +
1HS-(1N) все натурально

==== После конвенционного входа 2N, показывающего миноры
DBL - показывает силу; +
3C - оба мажора, черва не хуже пики; +
3D - оба мажора, пика лучше червы; +
3H/3S - натурально, отрицает длину в другом мажоре.

=== Шлемовая торговля
Класс cue-бидов не различается. При согласованной (или установленной как козырная) масти 4N в шлемовой торговле - всегда RKCB, иначе инвит в 6NT. +
Ответы на RKCB: 5C - 0-3 ценности из 5 (4 туза и король в согласованной масти); 5D - 1-4 ценности; 5H - 2-5 ценностей, нет козырной дамы; 5S - 2-5 ценностей, имеется козырная дама. +
После ответа на RKCB: `5 в ближайшую несогласованную масть` - вопрос о козырной даме (если соответствующей информации еще нет).

==== Конвенция Жозефин (применяется, только если не было блэквуда)
Заявка 5N просит поставить большой шлем при наличии в козырной масти 2х козырных фигур из ТКД, например: +
2H-5N - Жозефин

=== ИНТЕРВЕНЦИЯ
==== Вызывная контра
Обещает силу от 13 HCP. На открытие 1HS почти всегда обещает 4 в другом мажоре +
Ответы и дальнейшие заявки натуральны, но есть одно исключение: после контры на открытие оппонента 1C торговля развивается так же, как если бы контривший открыл 1C (т.е. 1D - негатив, имеется одвротка и проч.).

==== В затухающей позиции (на последней руке)
DBL может быть ослаблена. Переставка ответа партнера в 2C или в 2D не обещает сильного варианта. Переставка ответа партнера в 2H или 2S обещает сильный вариант.

==== Простой оверкол
`На первом уровне` 8-15 (`на 2-м уровне` - 10-15, `на 3-м уровне` - 12-17), 5+ натурально. +
Дальнейшая торговля натуральна; ответ 1N - 9-13, не отрицает 3-картный фит. +
`Новая масть без скачка` форсирует на 1-м и 3-м уровнях, не форсирует на 2-м. +
(1C)-1D-(P)-1HS, (1CD)-1H-(P)-1S - от 4 форсирует на круг, после этого есть чек-бэк

==== Специальные оверколы
После натуральных открытий 1DHS: +
`Кюбид` - 2-цвет со старшей из непоказанных мастей, до 10 или от 15 +
2N - 2-цвет в младших непоказанных мастях, до 10 или от 15 +
`Масть с прыжком` - одноцветный блок; +
`Кюбид c прыжком` - Gambling без задержки в масти открытия; +
3N - Gambling с задержкой в масти открытия.

На открытие оппонента 1C оверколы аналогичны открытиям (2D - Multi, 2H/2S - 2-цвет).

==== Бескозырные оверколы
===== Оверкол 1N
В прямой позиции - 15-17. +
В позиции реопен: 10-14 +
В позиции сэндвич, например, (1D)-P-(1H)-1N: 1N означает от 5-4 в непоказанных мастях.

В позиции P-(P)-P-(1HS) +
1N - миноры.

===== Оверкол 2N
После открытия на 2-м уровне - 15-18; +
(2CD)-2N-(P) - ? +
применяются Стейман 3C и трансферы 3D/3H +
(2HS)-2N-(P) - ? +
3C - трансфер в !d +
3D - трансфер в другой мажор +
`3 в мажор открывшегося` стейман

В позиции сэндвич - резкий расклад в непоказанных мастях +
В позиции балансирования - 4+-4+ в минорах;

==== Входы на открытие 1N
Против 1N применяются оверколы Multi-Landy:

DBL - =4 в мажоре от 5 в миноре, на что:

* 2C - до минора партнера
** 2D-2H - до мажора партнера (не устроил минор парта)
* 2D - до мажора партнера:
** 2HS-2N вопрос о миноре (не устроил мажор парта)
* 2HS - своя масть, от 6ки, не форс
* 3H - инвит в гейм в мажоре партнера

Если дана RDBL: P обещает 10+, остальное без изменений.

2C - от 5-4 в мажорах, на что:

* 2D - вопрос о лучшем (длиннейшем) мажоре, при равной длине о сильнейшем мажоре
* 2HS - контракт
* 3CD - своя масть, не форсирует
* 3HS - инвит в 4

Если контрят 2C: P трефа, 2D - бубна, RDBL - до лучшего мажора.

2D - мажорный одноцвет, на что торговля развивается как и после открытия малти.

Если контрят 2D: P - бубна, RDBL - до мажора, `масть` нат нефорс.

2HS - от 5-ки в объявленном мажоре и от 4-ки в миноре, на что:

* 2N до минора партнера
* 2S,3CD - натурально от 6ки, не форсирует
* 3HS - инвит в 4!h!s

Если контрят 2HS: RDBL - вопрос о второй масти, остальное нефорс. +
Если входят мастью: DBL до масти.

2N миноры.

=== ВИСТ

Из любого секвенса (обычного, внутреннего или ТК) ходят старшей. Из ТК против обычного контракта Т просит показать четность, К поощрение. (*Исключение*: против NT из ТК ходят королем; ход с туза против NT обещает сильную комбинацию и просит разблокировки.)

Из длинной масти, возглавляемой онером, ходят 4-й сверху, из пустой длинной масти - 2-й сверху. Из дублета старшей, из триплета средней.

Качественные и количественные сигналы - обратные: младшая карта показывает поощрение, либо четное количество карт. (Четность показывается от изначального количества карт).

Лавинталь - прямой. На проносах итальянские сигналы (*нечет* сила в масти).
Эхо Ленца - снос в козырной масти *старшей* фоски показывает возможность убитки.

=== Об авторах
Система Березка. Версия для Индивидуального Чемпионата Gambler построена на базе системы Березка для Индивидуального Чемпионата России по бриджу. +
Консультанты: Павел Воробей (Паша), Леонид Гринбаум (Lenya), Сергей Орлов (orel).

Общая редакция: Евгений Антонов (Mafus). 
