:linkcss:
:stylesdir: css/
:stylesheet: styles.css

:toc:
:toclevels: 4
:toc-title: Содержание

== Система торговли Французская натуральная

[sidebar]
Французская натуральная система торговли в бридже, используемая в клубе. Часто в общении применяется сокращение "фрнат". Используется при игре с автоподбором и в части индивидуальных турниров. Вист московский.

=== Открытия

    В отсутствие мажорных 5-ок называем длиннейший минор. При 3-3 открываем трефой, при 4-4 бубной (при желании показать и !c и !d на минимальной силе открываем 1!d имея 4-ку !d и 5-ку !c).

- 1C  11-21 hcp, от 3-ки !c (исключая 15-17 и 20-21 равномерного распределения).

- 1D  11-21 hcp, от 3-ки !d. 3-карты возможны только в раскладе 4-4-3-2.

- 1H,1S  11-21 hcp, от 5-ки !h,!s.

- 1N  15-17 hcp, равномерного распределения. Возможны минорные пятерки.

- 2C  гейм с руки, более 25 очков равномерного распределения или очень сильная масть. Не более 4 отдач от 17 очков

- 2D  Конвенция multi:

      а) мажорный полублок (6 карт в одном из мажоров, сила 5-10 hcp, очки в масти блока),
      б) 22-24 hcp равномерного распределения.

- 2H  от 5 карт в черве + от 5 в другой масти, сила 5-10 hcp.

- 2S  от 5 карт в пике + от 5 в миноре, сила 5-10 hcp.

- 2N  20-21 hcp равномерного распределения.

- `3-4 уровни`  все заявки - блоки по правилу безопасности (от 7 карт в масти):

        а) неблагоприятная зональность - без 2-х,
        б) равная зональность - без 3-х,
        в) благоприятная зональность - без 4-х.
        Например, 3!s “в зоне” против “до зоны” - 7 взяток при козыре пики с руки.

- 3N  Конвенция Gambling: ТКДВххх в миноре.

        а) Без боковых приемов до зоны.
        б) С боковым приемом (Т или Кх или Дхх) в зоне.

=== Ответы

==== 1C

* P  0-4 hcp
* 1D  от 4!d от 5 hcp (форсирует)
** 1H  4-ка !h, сила не уточняется
*** 1S   последовательность, которая не должна восприниматься как четвертая масть, сила не уточняется
* 1H  от 4!h от 5 hcp (форсирует)
** 1S  4-ка !s, сила не уточняется
*** 2D  (четвертая масть) - ФГ.
**** 2N  есть задержка в !d
**** 2H  3-ка !h
**** 3H  4-ка !h
** 1N  12-14 (первый диапазон), нет 4-ки !h, нет 4-ки !s, не форсирует
*** 2D  форсинг новым минором. В первую очередь показывается 3-ка !h
** 2N  18-19 (третий диапазон)
** 2C  12-14 от 5-ки !c, нет желания говорить NT (обычно с краткостью в !s)
** 2D  реверс, от 4-4 в !c-!d, от 16
** 2H  не форсирует, 4-ка !h, 12-15
** 3C  15-18 от 5-ки !c, не форсирует
** 3H  инвит, 4-ка !h, 16-19
** 3N  контракт на трефе
** 4H  контракт, 4-ка !h, 20-21 (не спешите делать такие заявки, заявите другие масти для форсинга)
* 1S  от 4!s от 5 hcp (форсирует)
** 2D  реверс, от 4-4 в !c-!d, от 16
** 2H  реверс, от 5-ки !c, 4-ка !h, от 16
* 1N  нет называемых 4-ок, 5-9 hcp (не форсирует)
* 2C  от 4-ки !c (фит), от 10 hcp (форсирует) - инвертированные миноры
* 2DHS  от хорошей 6-ки в масти (минимум 2 фигуры), от 12 hcp (ФГ)
* 2N  10-12 hcp, равномерного распределения (не форсирует)
* 3C  от 5-ки !c, 0-7 hcp (блок)
* 3N  13-15 hcp равномерного распределения

==== 1D

* `всё аналогично 1!c`
* 1H  4-ка !h
** 1N  12-14 (первый диапазон), нет 4-ки !h, нет 4-ки !s, не форсирует
** 2C  от 4-ки !c, нет 4-ки !h, нет 4-ки !s, форсирует
* 2C  от 10 hcp, от 4-ки !c (форсирует). Если сила до 9 hcp, то переходить на второй уровень нельзя.
** 2D  удлиняет !d, минимум
** 2M  4-ка, не усиливает, форсирует
** 2N  усиливает, от 14
** 3C  от 5-4 в !d,!c
* `все остальные заявки` - ФГ

==== 1H

* P  0-4 hcp
* 1S  от 4!s от 5 hcp (форсирует)
** 1N  11-15 (первый диапазон), нет 4-ки !s, не форсирует
** 2C  натурально от 5-4, не форсирует, но можно пасовать только на минимуме (5-6 hcp)
*** 2D  (четвертая масть) - ФГ.
**** 2N  есть задержка в !d
**** 2H  не удлиняет !h
**** 2S  3-ка !s
** 2H  не форсирует, от 6-ки !h
** 2N  16-19, 5-3-3-2
** 3m  от 5-5, от 17, для партнера это ФГ
** 3N  20-21 (третий диапазон)
* 1N  нет 4-ки !s, 5-9 hcp (не форсирует)
** 2C  натурально от 5-4, не форсирует, но можно пасовать только на минимуме (5-6 hcp)
** 2H  не форсирует, от 6-ки !h
** 2N  инвит
* 2C
** 2D  не усиливает, от 5-4 (Фр)
*** 2H  с дуплетом !h и до 12 hcp
*** 2N  без надвышек и без червей
*** 3C  с надвышками - заявка на 3ем уровне
*** 3D  фит в бубне
*** 3H  инвит к гейму с фитом !h (10-12 hcp).
* 2m  от 10 hcp, от 4-ки в !c, !d (форсирует на круг). В заявленной масти (!c, !d) возможна 3-ка, если отвечающий имеет 3-хкартный фит в мажор партнёра и силу от 10-ти hcp.
** 2H  не форсирует, не удлиняет !h, нет 4-ки !c, !d
** 2S  реверс, от 16, 4-ка !s, ФГ
** 2N  от 14, ФГ
** 3m  от 4-ки в миноре
* 2H  5-9 hcp, фит (от 3-х карт в !h)
* 2S  от хорошей 6-ки !s, от 12 hcp (ФГ)
* 2N  от 4-ки !h, от 10 hcp, т.е. от инвита к гейму
** 3m  показ ценностей, инвит пока не принят
** 3H  инвит не принят
** 3S,4m  кюбид
** 4H  вялый приём
* 3H  от 4-ки !h, от 0-7 hcp (блок)
* 3N  13-15 hcp равномерного распределения
* 4N  RKCB - вопрос о ключевых картах

==== 1S

* `всё аналогично 1!h`
* 2H  от 10 hcp, от 5-ки !h или с фитом в пике

==== 1N

* 2C  от 8 hcp, есть 4-ка !h и/или !s, вопрос о мажорных четверках (конвенция Стейман)
** 2D  нет мажорных четверок
*** 2H  от 5-ки !h и 4-ка !s
*** 2S  от 5-ки !s и 4-ка !h
*** 2N  8-9 hcp (инвит к 3NT)
*** 3N  от 10 hcp, нет шлемового интереса
*** 4N  инвит в шлемик
** 2H  4-ка !h, не исключена 4-ка !s
** 2S  4-ка !s
** `других заявок нет`

* 2D  трансфер в черву (от 5-ки !h, от 0 hcp)
** 2H  в любом случае, кроме исключений (см. ниже)
*** 2N  инвит к 3NT, 8-9 hcp, расклад 5-3-3-2
*** 3CD  ФГ, натурально
*** 3H  инвит, от 6-ки
*** 3N  10-14 hcp (геймовый баланс)
** 2N  3-картный фит с 2-мя фигурами, максимум силы (17 hcp)
** 3H  4-картный фит с фигурой, максимум
* 2H  трансфер в !s, полная аналогия с трансфером в !h
* 2S

      а) инвит к 3NT, 8-9 hcp без мажорных 4-рок
      б) трансфер в !c

** 2N  15-16 hcp, инвит не принят
*** P  если был инвит
*** 3C  слабый с трефами, если был трансфер.
*** `Другие заявки` натуральны, ФГ

** 3C  17 hcp, инвит принят
*** 3N  если был инвит
*** P  если слабый с трефами.
*** `Другие заявки` натуральны, ФГ

* 2N  трансфер в !d
** 3C  сильный приём трансфера: максимум и есть фигурный фит в бубну
** 3D  во всех остальных случаях
* 3CDHS  от 15 hcp, масть от 5-ти карт, сильная (лучше 6-ка), форсирует, шлемовый интерес
** 3N  нет фита
** 4CDHS  фит
* 3N  контракт (10-14, нет интереса к гейму в масти или шлему)
* 4C  Вопрос о тузах (конвенция Гербер)
** 4D  0 или 3
** 4H  1 или 4 (по аналогии с 0314)
** 4S  2+0 королей
** 4N  2+1 король и т.д.
* 4N  прямой инвит в шлемик

==== 2C

* 2D  негатив: нет 3-х контролей. (Туз=2 контроля, Король=1 контроль)
** 2HS  очень сильная масть
** 2N  от 25 hcp равномерного распределения
*** 3C  конвенция Барон
** 3CD  очень сильная масть
* 2HS  позитив: не менее 3-х контролей, от 4-ки !h, !s
* 3CD  позитив: не менее 3-х контролей, от 4-ки !c, !d
* 2N  полупозитив: нет 3-х контролей, есть от 8 hcp

      далее открывающий показывает свой вариант - мастью или NT, отвечающий - фитует или нет. В отсутствии фита вторая масть - натурально. При сфитованной масти открывающий показывает кюбиды первого класса, отвечающий может второго.

==== 2D

* 2H  в любом случае, кроме описанных ниже
** P  червовый полублок
** 2S  пиковый полублок
** 2N  сильный вариант (22-24)
*** 3C  Барон
*** 3D  трансфер в черву
*** 3H  трансфер в пику
*** 3N  контракт
* 2S  есть поддержка в !h, инвит к гейму
** P  пиковый полублок
** 3H  червовый полублок (минимум)
** 4H  червовый полублок (максимум)
** 2N  сильный вариант (22-24)
*** 3C  Барон
*** 3D  трансфер в черву
*** 3H  трансфер в пику
*** 3N  контракт
* 2N  от 15 hcp
** 3C  максимум червового полублока
** 3D  максимум пикового полублока
** 3H  минимум червового полублока
** 3S  минимум пикового полублока
* 3H  есть поддержка к любому мажору, до масти, чаще носит подблокирующий характер
* 4H  есть поддержка к любому мажору, до масти, готов играть раскладной гейм

==== 2H

* P  натурально
* 2S  слабый поиск второй масти
** P  пика
** 3C  трефа
** 3D  бубна
* 2N  сильный вопрос о второй масти
** 3C  трефа
** 3D  бубна
** 3H  черва с пикой

==== 2S

* P  натурально
* 2N  сильный вопрос о миноре. Ответ натурально
** 3C  трефа
** 3D  бубна
* 3C  слабый поиск минора. Ответ натурально
** P  трефа
** 3D  бубна

==== 2N

* 3C  Барон
* 3DH  Техас в !h, !s
* 3S  слабая минорная рука, желание играть контракт 4!c или 4!d
* 4CD  натурально, форсирует
* 4N  инвит в шлемик

==== 3N

* P  есть задержки и как минимум синглет в предполагаемом миноре
* 4C  нет задержек, поиск минора

====  Конвенция Baron (вопрос о ближайшей четвёрке)

Используется в секвенциях

2N (20-21) -3C! +
2D-2HS-2N (22-24) -3C! +
2C-2DHS-2N (от 25 рр) -3C! +

2N

* 3C!  Барон

  Ответы натурально, 3NT показывает 4+ трефы.

** 3D  от 4-ки !d
*** 3H
**** 3S  4-ка !s
***** 4S
** 3HS  4-ка !h, !s
** 3N  от 4-ки !c

=== Шлемовая торговля

      Строится на конвенциях RKCB, Жозефин и кюбидах. В отсутствии явно согласованной масти, согласованной для вопросов считается последняя названная натурально.

      Кюбид первого класса - Туз или ренонс. Кюбид второго класса - Король или синглет. Показывается ближайший кюбид любого класса. Повтор согласованной масти - отсутствие непоказанных кюбидов.

====  Конвенция Жозефин

      заявка 5NT просит поставить Большой шлем в согласованной масти при наличии в ней двух фигур из ТКД и малый в противном случае.

====  Ответы на RKCB-0314 (Key Cards (KC) - Тузы и Козырной король)

* 4N  RKCB всегда, кроме 1N-4N - прямой инвит.

** 5C  0 или 3 KC
** 5D  1 или 4 KC
** 5H  2 KC, нет козырной дамы
** 5S  2 KC, есть козырная дама

      Если был ответ 1/4 или 0/3 , то
        следующий шаг (в несогласованную масть) - вопрос о даме,
        через один шаг - вопрос о королях.

      Ответы на вопрос о даме: 1 шаг - нет, 2-ой - есть.
      Ответы на вопрос о королях: 1 шаг - 0 королей, 2-ой - 1 и т.д.

      Если оппоненты входят мастью или контрой на наше заявление 4NT (RKCB), то DOPI-ROPI:
        контра или реконтра - 0/3 туза,
        пас - 1/4 туза,
        следующая масть - 2/5 без дамы.

===   Интервенция (конкурентная торговля)

      Вход мастью: 8-15 hcp, от 5-ки в масти.

      Основные принципы входа в интервенцию мастью состоят в том, что масть должна быть плотной.

      Входим мастью от 8 очков на первом уровне, от (10)11 на втором и от (13)14 на третьем.

      Прыжковый вход всегда является блоком по правилу безопасности.

====  Контра (призывная)

      а) от 12 hcp+ min 3-ка в каждой масти, кроме масти открытия оппонента,
      б) от 16 hcp + 5-ти карточная масть.

      Ответы (все назначения отвечающего после призывной контры партнера натуральные и не форсируют.
      Единственный форсинг - масть оппонентов):
        0 - 9 hcp: называем ближайшую масть от четырех карт,
        7 - 9 hcp, примерно бескозырный расклад с задержкой в масти противников: 1NT,
        9 - 12 hcp, с хорошей задержкой в масти противников: 2NT,
        9 - 12 hcp, не менее пятерки (или без задержки в масти противника): прыжок в своей масти,
        от 13 hcp либо очень резкая рука: повтор масти оппонента (1!h-контра-пас-2!h) - ФГ,
        7 - 9 hcp и не менее хорошей пятерки в масти открытия: пас.

      в) от 9 hcp и 4-4 в мажорах на четвертой руке в торговле 1!c(!d) - пас - пас.


====  Контра (негативная)

от 8 hcp. показывает оставшиеся масти, например:

1D-(1H)-DBL  ровно четверка пик, нет бубнового фита, в трефе что-то есть +
1H-(2D)-DBL  есть очки, трефа и пика, нет хорошей натуральной заявки

====  Реконтра (на призывную контру оппонентов)

от 10 hcp, обычно нет фита

====  Повторение масти оппонента

(1C)-2C  натурально, от 10, от хорошей 5-ки +
(1D)-2D  от 5-5 пика с червой или трефой +
(1H)-2H  от 5-5 пика с минором +
(1S)-2S  от 5-5 черва с минором

====  2NT на открытие оппонентов на 1 уровне

(1D)-2N  черва с трефой +
(1HS)-2N  миноры

====  2NT на полублок оппонентов

показывает задержку в масти блока и силу 16-19, (или компенсирующие ценности, например, длинная самостоятельная масть).

      Тоже 2NT натурально на заявку 2!d (мульти), задержка должна быть в обоих мажорах.

===   Двусторонняя торговля

2-ой уровень не форсирует, например:

1H-(1S)-2D  нефорс, через контру - сильнее.

На 1!c оппонентов: (1C)-2DHS - натуральные полублоки;

1N-(DBL)-

* 2CDHS  слабость, убегание в масть
* RDBL  наказательная, от 7 hcp

====  На 1NT оппонентов (конвенция мульти-Ленди)

(1N)

* DBL  от силы NT оппонентов, например, 1NT (15-17) - контра (от 15);
* 2C  от 5-4 в мажорах
* 2D  мажорная 6-ка
* 2M  от 5-4 мажор с минором
* 2N  миноры

===   Вист Московский

Первый ход:

      из дуплета - старшей,

      из триплета - средней, потом старшую,

      из ряда фосок - второй,

      из под фигуры - четвертой (правило 11);

      из плотности - старшей (КДВ, В109),

      из внутренней плотности - старшей (КВ109).

Поощрение: мелкими.

В масть (обратная четность):

      четное число карт - мелкая, старшая,

      нечетное число карт - средняя (старшая) фоска, мелкая.

На проносах (итальянские сигналы):

      нечетная фоска - сила в масти сноса,

      мелкая четная фоска - сила в младшей масти (исключая масти хода и сноса),

      крупная четная фоска - сила в старшей масти.

Ход на убитку (Лавинталь):

      мелкая - возврат по младшей масти (исключая масти хода и козыря),

      крупная - возврат по старшей масти.

===  Сокращения

      hcp - high-card points, фигурные очки.
      Подсчет hcp: Туз - 4, Король - 3, Дама - 2, Валет - 1.

      м - минор: трефа или бубна,

      М - мажор: черва или пика.

      Фит - от 8-ми карт на линии, т.е. если у партнеров в некой масти 5+3, 4+4 или 6+3 карт, то у них есть фит (в последнем случае - девятикартный).

      Форсирует - партнер не имеет права пасовать, какая бы карта у него ни была, если, конечно, оппоненты не вступали в торговлю.

      ФГ - форсинг до гейма, нельзя пасовать ниже уровня гейма. Основное назначение заявок в позиции ФГ - поиск шлема, быстрый прыжок в гейм (после ФГ) - минимум, нет шлемового интереса.

      Фр - форсинг-раунд, форсинг на круг торговли

      Инвит - приглашение, не принимается, если у вас минимум того, что вы показали предыдущей торговлей.

      Реверс - невынужденное называние старшей масти, показывает сильную руку.

===  Общие принципы натуральной торговли

      новая масть - форсирует
      скачок - инвитирует
      новая масть со скачком - ФГ
      NT и повтор масти на ближайшем уровне - не форсирует

===  Приблизительный уровень контрактов

      частичный контракт (1-2NT, 1-3 в мажорах, 1-4 в минорах) - от 18 очков (hcp),
      гейм в NT (3-5NT) - от 25,
      гейм в мажорах (4-5 в !h, !s) - от 26,
      гейм в минорах (5!c, 5!d) - от 28,
      малый шлем (6 в масти и NT) - от 31,
      большой шлем (7 в масти и NT) - от 34.

      При меньшем количестве hcp высокая игра возможна при наличии длинных мастей, а для козырных контрактов - ренонсов, синглетов, пустых дуплетов, фита 4-4 и пр.


Система основана на материалах сайта www.bridgeclub.ru, благодарим за это Наталью Женову aka БелаяПушиста. 
